chain = input('Введите последовательность нуклеотидов английскими буквами: \n').upper()
a = chain.count('A')
g = chain.count('G')
t = chain.count('T')
c = chain.count('C')
leng = len(chain)
ad = round(a*100/leng, 1)
gu = round(g*100/leng, 1)
ti = round(t*100/leng, 1)
ci = round(c*100/leng, 1)
print('>>>Результат анализа<<<')
print(f'''Количество нуклеотидов
А = {a}({ad}%)
T = {t}({ti}%)
G = {g}({gu}%)
C = {c}({ci}%)''')
print(f'Общая длина: {leng}')